# Generated by Django 5.2.6 on 2025-09-22 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_date',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
