# Generated by Django 5.2.6 on 2025-09-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_meeting_meeting_date_meeting_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('TEAM', 'Team'), ('PROJECT', 'Project'), ('BRAINSTORM', 'Brainstorm'), ('REVIEW', 'Review')], default='TEAM', max_length=20),
        ),
    ]
