# Generated by Django 5.2.6 on 2025-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGEMENT', 'Management'), ('MANAGER', 'Manager')], default='MANAGER', max_length=50),
        ),
    ]
